/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jsudoku;

/**
 *
 * @author mathieu
 */
public class JHelpDesk extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public JHelpDesk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTutor = new javax.swing.JLabel();
        JAsk = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        JMore = new javax.swing.JButton();
        JOk = new javax.swing.JButton();
        JMiddle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JInfoBox = new javax.swing.JTextPane();

        setMaximumSize(new java.awt.Dimension(300, 1000));
        setLayout(new java.awt.BorderLayout());

        JTutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jsudoku/tutor.jpg"))); // NOI18N
        JTutor.setText("jLabel1");
        JTutor.setMaximumSize(new java.awt.Dimension(120, 120));
        JTutor.setMinimumSize(new java.awt.Dimension(120, 120));
        JTutor.setPreferredSize(new java.awt.Dimension(30, 30));
        add(JTutor, java.awt.BorderLayout.NORTH);

        JAsk.setText("Help me!");
        add(JAsk, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        JMore.setText("I need more help");
        jPanel1.add(JMore);

        JOk.setText("I understand");
        jPanel1.add(JOk);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        JInfoBox.setEnabled(false);
        JInfoBox.setMaximumSize(new java.awt.Dimension(50, 1024));
        jScrollPane1.setViewportView(JInfoBox);

        javax.swing.GroupLayout JMiddleLayout = new javax.swing.GroupLayout(JMiddle);
        JMiddle.setLayout(JMiddleLayout);
        JMiddleLayout.setHorizontalGroup(
            JMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1183, Short.MAX_VALUE)
            .addGroup(JMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JMiddleLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JMiddleLayout.setVerticalGroup(
            JMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1041, Short.MAX_VALUE)
            .addGroup(JMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JMiddleLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        add(JMiddle, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JAsk;
    private javax.swing.JTextPane JInfoBox;
    private javax.swing.JPanel JMiddle;
    private javax.swing.JButton JMore;
    private javax.swing.JButton JOk;
    private javax.swing.JLabel JTutor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
