/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jsudoku;

import java.awt.List;
import static java.lang.Math.sqrt;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Map.Entry;
import java.util.Set;
import javax.swing.JButton;
import javax.swing.JToggleButton;

/**
 *
 * @author mathieu
 */
public class JPoss extends javax.swing.JFrame {

    
    JSudokuCase jcase;
    LinkedList<JToggleButton> but = new LinkedList<JToggleButton>();
    /**
     * Creates new form JPoss
     * @param <error>
     */
    public JPoss(JSudokuCase _case) {
        jcase = _case;
        //initComponents();
        init();
    }
    
    public void init(){
        
        int size = (int) Math.ceil(sqrt(jcase.tr.size()));
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(size, size));

        Set<Entry<Integer,Boolean>> s = jcase.tr.entrySet();
        Iterator<Entry<Integer,Boolean>> it = s.iterator();
        for (Entry<Integer,Boolean> ent : jcase.tr.entrySet()){
            JToggleButton jb = new JToggleButton();
            jb.setText(Integer.toString(ent.getKey()));
            jb.setSelected(ent.getValue());
            jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
            });
            but.add(jb);
            getContentPane().add(jb);

        }
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        JB1 = new javax.swing.JButton();
        JB2 = new javax.swing.JButton();
        JB3 = new javax.swing.JButton();
        JB4 = new javax.swing.JButton();
        JB5 = new javax.swing.JButton();
        JB6 = new javax.swing.JButton();
        JB7 = new javax.swing.JButton();
        JB8 = new javax.swing.JButton();
        JB9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 3));

        JB1.setText("jButton1");
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });
        getContentPane().add(JB1);

        JB2.setText("jButton1");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, JB3, org.jdesktop.beansbinding.ELProperty.create("${selected}"), JB2, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        getContentPane().add(JB2);

        JB3.setText("jButton1");
        getContentPane().add(JB3);

        JB4.setText("jButton1");
        getContentPane().add(JB4);

        JB5.setText("jButton1");
        getContentPane().add(JB5);

        JB6.setText("jButton1");
        getContentPane().add(JB6);

        JB7.setText("jButton1");
        getContentPane().add(JB7);

        JB8.setText("jButton1");
        getContentPane().add(JB8);

        JB9.setText("jButton1");
        getContentPane().add(JB9);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        
    }//GEN-LAST:event_JB1ActionPerformed

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {
        JToggleButton b = (JToggleButton)evt.getSource();
        int num = Integer.parseInt(b.getText());
        jcase.tr.put(num, b.isSelected());
    }
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB2;
    private javax.swing.JButton JB3;
    private javax.swing.JButton JB4;
    private javax.swing.JButton JB5;
    private javax.swing.JButton JB6;
    private javax.swing.JButton JB7;
    private javax.swing.JButton JB8;
    private javax.swing.JButton JB9;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
